config/routes.rb
Rails.application.routes.draw do
  root "welcome#home"
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  get '/parks/most_visits' => 'parks#most_visits'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  #custom routes above generator provided routes
  
  resources :parks do
    resources :visits, only: [:index, :new, :create]
  end
  resources :users
  resources :dogs
  resources :visits  
  resources :playdates

    #For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/park.rb
class Park < ApplicationRecord
    has_many :visits
    has_many :dogs, through: :visits

    scope :visits_count

    def active_visits
        self.visits.active_visit
    end

    def active_visits_count
        active_visits.count
    end

    def dogs_at_park
        Dog.joins(:visits).where({visits: {active_visit: true, park: self}})
    end

    def most_visits
        Park.joins(:visits).group("parks.id").order("count(visits.id) DESC")
    end

end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
    include ParksHelper
    
    def index
        @parks = Park.all
    end
    
    def show
        @park = Park.find(params[:id])
    end

    def most_visits
        @park = Park.find_by_sql("SELECT * FROM parks INNER JOIN visits ON visit.park_id = park.id GROUP BY park.id ORDER BY COUNT(visits.id) DESC")
    end

    def edit
    end

    def update
    end

end

app/helpers/parks_helper.rb
module ParksHelper




    def active_visits_by_park_dog_user(park)
        Visit.active_visit.joins(dog: :user).where({ park: park, dog: {user: current_user} })
    end

    
    def count_dogs_at_park(park)
        park.dogs_at_park.count
    end


end

app/views/parks/index.html.erb
<h1> Parks Index </h1>

<ul>
    <% @parks.each do |park| %>
        <li> <%= park.name %> </li>
        <li> <%= "Current Visitors: " + park.current_visitors.to_s %> </li>
        <li> <%= link_to "See park details", park_path(park) %> </li>
        <br>

    <% end %>
</ul>

app/views/parks/most_visits.html.erb
<%= @park.name%>

app/views/parks/park.html.erb
<h1><%= @park.name %></h1>

<h3>Check Into Park: </h3>

app/views/parks/show.html.erb
<h1><%= @park.name %></h1>



<h3><%= link_to "Check-in to Park", new_park_visit_path(@park) if current_user.dogs.any?%></h3>
<% active_visits_by_park_dog_user(@park).each do |visit| %>
    <h3><%= link_to "Check #{visit.dog.name} Out of Park", edit_visit_path(visit)%></h3>
<% end %>

<br>
<br>
<%= "Current Visitors: #{count_dogs_at_park(@park)}" %>
<br>
<br>
<%= link_to "See Who's At Park", park_visits_path(@park) %>