config/routes.rb
Rails.application.routes.draw do
  root "welcome#home"
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  get '/parks/most_visits' => 'parks#most_visits'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  #custom routes above generator provided routes
  
  resources :parks do
    resources :visits, only: [:index, :new, :create]
  end
  resources :users
  resources :dogs
  resources :visits  
  resources :playdates

    #For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_many :visits, :dependent => :destroy
  has_many :parks, through: :visits
  has_many :playdates, through: :visits

  validates :name, presence: true
  validates :age, numericality: true

  #scope :my_dogs, -> { where(user_id: current_user.id) }


  def has_active_visit?
    self.visits.active_visit.any?
  end


end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
include DogsHelper

    def index
        @dogs = Dog.all
    end

    def show
        @dog = Dog.find(params[:id])
    end

    def new
        @dog = Dog.new(user_id: current_user.id)
    end

    def create
        binding.pry
        @dog = Dog.new(dog_params)
        @dog.user = current_user
        if @dog.save
            redirect_to dog_path(@dog)
        else
            render :new
        end
    end

    def edit
        @dog = Dog.find(params[:id])
    end

    def update
        @dog = Dog.find(params[:id])
        if edit_dog_allowed?(@dog) && @dog.update(dog_params)
            redirect_to dog_path(@dog)
        else
            flash[:message] = "That's not your dog!"
            render :edit
        end
    end

    def destroy
        @dog = Dog.find(params[:id])
        if edit_dog_allowed?(@dog)
            @dog.destroy
        end
        redirect_to dogs_path
    end

    private

    def dog_params
        params.require(:dog).permit(:name, :age, :breed, :size, :user_id)
    end

end

app/helpers/dogs_helper.rb
module DogsHelper

    def edit_dog_allowed?(dog)
        dog.user == current_user
    end
end

app/views/dogs/_form.html.erb
    <%= f.label :name%>
    <%= f.text_field :name %>
    <br>
    <br>
    <%= f.label :age %>
    <%= f.number_field :age %>
    <br>
    <br>
    <%= f.label :breed %>
    <%= f.text_field :breed %>
    <br>
    <br>
    <%= f.label :size %>
    <%= f.text_field :size %>
    <br>
    <br>

    <%= f.submit "Submit" %>

app/views/dogs/edit.html.erb
<h1>Edit Your Dog</h1>

<%= flash[:message] if flash[:message]%>

<%= form_for(@dog) do |f| %>

    <%= render partial: 'form', locals: { f: f } %>    

<% end%>

app/views/dogs/index.html.erb
<h1>Dogs</h1>

<ul>
<% @dogs.each do |dog| %>
    <li><%= dog.name%></li>
    <li>"Visit Active Status"</li>
    <li><%= link_to "View Dogs Profile", dog_path(dog) %></li>
    <br>
<% end %>
</ul>

app/views/dogs/new.html.erb
<h1>Create Your Dog</h1>

<%= flash[:message] if flash[:message]%>

<%= form_for(@dog) do |f| %>

    <%= render partial: 'form', locals: { f: f } %>    

<% end%>

app/views/dogs/show.html.erb
<h1><%= @dog.name + "'s Showpage" %></h1>

<% if @dog.user == current_user %>
    <h3><%= link_to "Edit Dog", edit_dog_path(@dog)%></h3>
    <h3><%= link_to "Delete Dog", dog_path(@dog), method:"delete"%></h3>
<% end %>

<p>Age: <%= @dog.age %></p>
<p>Breed: <%= @dog.breed %></p>
<p>Size: <%= @dog.size %></p>
<p>Disposition: <%= @dog.disposition %></p>
<p>Favorite Toy: <%= @dog.favorite_toy %></p>
<p>Favorite Game: <%= @dog.favorite_game %></p>