config/routes.rb
Rails.application.routes.draw do
  root "welcome#home"
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  get '/parks/most_visits' => 'parks#most_visits'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  #custom routes above generator provided routes
  
  resources :parks do
    resources :visits, only: [:index, :new, :create]
  end
  resources :users
  resources :dogs
  resources :visits  
  resources :playdates

    #For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :dog
  belongs_to :park
  has_many :visit_playdates
  has_many :playdates, through: :visit_playdates


  scope :active_visit, -> { where(active_visit: true) }

  def visiting_dog_name
    self.dog.name
  end

  def self.active_visits_by_park(park_id)
    self.active_visit.where(park: park_id)
  end


end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
    #before_action :current_user_dog?, only: [:create, :edit, :update]
    include VisitsHelper

    def index
        if params[:park_id]
            @visits = Visit.active_visits_by_park(params[:park_id])
        else
            @visits = Visit.all
        end
    end

    def show

    end

    def new
        @visit = Visit.new(park_id: params[:park_id])
    end

    def create       
        @visit = Visit.new(visit_params)
        if create_visit_allowed?(@visit)
            @visit.active_visit = true
            if @visit.save
                redirect_to park_path(@visit.park)
            else
                render :new
            end
        else
            flash[:message] = "Dog cannot have two visits at same time."
            render :new
        end
    end

    def edit
        @visit = Visit.find(params[:id])
    end

    def update
        @visit = Visit.find(params[:id])
        if @visit.dog.user_id == current_user.id && @visit.update(active_visit: false)
            redirect_to parks_path
        else
            render park_path(@visit.park)
        end
    end

    private

    def visit_params
        params.require(:visit).permit(:dog_id, :park_id, :id)
    end

end

app/helpers/visits_helper.rb
module VisitsHelper

    def create_visit_allowed?(visit)
        !visit.dog.has_active_visit? && visit.dog.user == current_user
    end




end

app/views/visits/_form.html.erb
    <%= f.collection_select :dog_id, current_user.dogs.all, :id, :name %>
    <br>
    <br>
    <%= f.submit "Submit" %>

app/views/visits/edit.html.erb
<h1> Check-out of Current Visit </h1>



<%= form_for(@visit) do |f| %>

    <%= render partial: 'form', locals: { f: f } %>    

<% end%>

app/views/visits/index.html.erb
<h1>Visits Index</h1>

<% @visits.each do |visit|%>
    <%= link_to visit.dog.name, dog_path(visit.dog)%>
    <br>
<% end %>

app/views/visits/new.html.erb
<h1>Check-In to Park</h1>

<%= flash[:message] if flash[:message]%>

<%= form_for(@visit) do |f| %>
    <%= f.hidden_field :park_id, value: @visit.park_id %>
    <%= render partial: 'form', locals: { f: f } %>    

<% end%>

app/views/visits/show.html.erb
<h1>Visit</h1>