config/routes.rb
Rails.application.routes.draw do
  root "welcome#home"
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  get '/parks/most_visits' => 'parks#most_visits'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  #custom routes above generator provided routes
  
  resources :parks do
    resources :visits, only: [:index, :new, :create]
  end
  resources :users
  resources :dogs
  resources :visits  
  resources :playdates

    #For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :username, presence: true, uniqueness: true
    validates :email, uniqueness: true

    has_many :dogs


    def self.from_omniauth(response)
        User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u|
            u.username = response[:info][:name]
            u.email = response[:info][:email]
            u.password = SecureRandom.hex(15)
        end
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :redirect_if_not_logged_in, only: [:new, :create]
        
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            flash[:error] = @user.errors.full_messages.to_sentence
            render :new
        end
    end

    def show
        user = User.find_by(id: params[:id])
        if user == current_user
            user_path(user)
        else
            redirect_to '/'
        end
    end

    
    private
    
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= flash[:error] if flash[:error]%>
<br>
<br>

<%= form_for(@user) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <br>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <br>
    <br>
    <%= f.label :password%>
    <%= f.password_field :password %>
    <br>
    <br>
    <%= f.submit "Submit" %>
<% end%>

<%= button_to "Signup With Google", "/auth/google_oauth2"%>

app/views/users/show.html.erb
<h1>Hello User</h1>

<%= link_to "Enter Your Dog", new_dog_path %>